SELECT * FROM PROFESSOR;
--1. BONUS를 받는 교수들 출략
SELECT * FROM PROFESSOR
WHERE BONUS>1;
--2. 급여가 300~400 사이인 교수들 출력
SELECT * FROM PROFESSOR
WHERE PAY BETWEEN 300 AND 400;
--3. 아이디에 'a'가 들어가는 교수 출력
SELECT * FROM PROFESSOR
WHERE ID LIKE '%a%';
--4. PROFNO, NAME, ID를 임의로 넣어서 교수 레코드 INSERT
INSERT INTO PROFESSOR (profno,NAME,ID)
VALUES (1121, '홍길동' ,'fasfsafsa');
COMMIT;
--5 4.번에서 만든 데이터 DELETE
DELETE FROM PROFESSOR WHERE PROFNO = '1121';
COMMIT;
--6. 급여가 300이하인 교수들의 급여를 +10 UPDATE
UPDATE PROFESSOR SET 
PAY = PAY+10
WHERE PAY<=300;
SELECT * FROM PROFESSOR;
COMMIT;