SELECT * FROM STUDENT
--WHERE STU_HEIGHT >=165 AND STU_HEIGHT<=175;
WHERE STU_HEIGHT BETWEEN 165 AND 175;

SELECT *
FROM PROFESSOR
WHERE POSITION IN ('정교수','조교수');
--WHERE POSITION = '정교수' OR POSITION = '조교수';

SELECT *
FROM PROFESSOR
WHERE POSITION LIKE '%교수%';


INSERT INTO STUDENT(STU_NO, STU_NAME, STU_DEPT)
VALUES(12345678,'홍길동', '기계');

SELECT *
FROM STUDENT;
COMMIT;
INSERT INTO STUDENT
VALUES(12341234,'김철수','전기전자',1,'A','M',170,NULL);

-- 학번이 12345678(홍길동)인 학생의 학과 '컴퓨터정보' , 학년을 1, CLASS를 'A'로 수정
UPDATE STUDENT SET
STU_DEPT = '컴퓨터정보', 
STU_GRADE = 1,
STU_CLASS = 'A'
WHERE STU_NO = 12345678;

--DELETE
--학번이 12341234이 학생 삭제
DELETE FROM STUDENT WHERE STU_NO = '12341234';
