--그룹 함수
--SUM, AVG ,MAX, MIN ,COUNT
SELECT SUM(PAY)
FROM PROFESSOR;

SELECT AVG(PAY)
FROM PROFESSOR;

SELECT MAX(PAY)
FROM PROFESSOR;

SELECT MIN(PAY)
FROM PROFESSOR;

SELECT COUNT(*),COUNT(BONUS)
FROM PROFESSOR;

SELECT *
FROM PROFESSOR;

SELECT POSITION , AVG(PAY)
FROM PROFESSOR
GROUP BY POSITION;

SELECT STU_DEPT,STU_GENDER,AVG(STU_HEIGHT)
FROM STUDENT
WHERE STU_GENDER IS NOT NULL
GROUP BY STU_DEPT, STU_GENDER;

SELECT * FROM PROFESSOR;

SELECT POSITION, MAX(PAY)
FROM PROFESSOR
GROUP BY POSITION;

--그룹함수에서 조건
SELECT STU_DEPT, COUNT(*)
FROM STUDENT
GROUP BY STU_DEPT
HAVING COUNT(*) >= 4;

SELECT * FROM PROFESSOR;
-- 각 직급(POSITION)별 급여 평균 300 이상
--직급 ,평균 급여 출력
SELECT POSITION, ROUND(AVG(PAY), 1)
FROM PROFESSOR
GROUP BY POSITION
HAVING AVG(PAY) >=300;


