--서브쿼리
SELECT MAX(PAY)
FROM PROFESSOR;

SELECT *
FROM PROFESSOR
WHERE PAY = (
SELECT MAX(PAY)
FROM PROFESSOR
);


SELECT *
FROM PROFESSOR
WHERE (POSITION,PAY) IN(
    SELECT POSITION, MAX(PAY)
    FROM PROFESSOR
    GROUP BY POSITION
);
--STUDNET 테이블에서 키가 가장 큰 사람과 가장 작은 사람의
--학번,이름, 학과 키 출력

SELECT MAX(STU_HEIGHT)
FROM STUDENT;
SELECT MIN(STU_HEIGHT)
FROM STUDENT;

SELECT STU_NO, STU_NAME, STU_DEPT, STU_HEIGHT
FROM STUDENT
WHERE STU_HEIGHT = (
    SELECT MAX(STU_HEIGHT)
    FROM STUDENT
)OR STU_HEIGHT = (
    SELECT MIN(STU_HEIGHT)
    FROM STUDENT
);





