--조인

SELECT *
FROM STUDENT;

SELECT *
FROM ENROL;
SELECT *
FROM SUBJECT;

SELECT *
FROM student
INNER JOIN ENROL ON STUDENT.STU_NO = ENROL.STU_NO; 

SELECT S.STU_NO, STU_NAME ,ENR_GRADE
FROM student S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO; 

SELECT S.STU_NO, STU_NAME ,ENR_GRADE, E.SUB_NO, SUB_NAME
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO 
INNER JOIN SUBJECT SUB ON SUB.SUB_NO = E.SUB_NO;


SELECT *
FROM EMP;
SELECT *
FROM DEPT;
SELECT *
FROM SALGRADE;
SELECT ENAME, DNAME, SAL , EMPNO
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;

--STUDENT, ENROL ,SUBJECT
--1.학생들의 시험 평균 점수 구하기(학번, 이름. 평균점수)
--2.학과별 시험 평균점수 구하기
SELECT S.STU_NO, STU_NAME ,ENR_GRADE, E.SUB_NO, SUB_NAME
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO 
INNER JOIN SUBJECT SUB ON SUB.SUB_NO = E.SUB_NO;
