CREATE OR REPLACE VIEW STUDENT_VIEW AS
SELECT STU_NO,STU_NAME,STU_DEPT
FROM STUDENT
WHERE STU_DEPT = '기계'
WITH READ ONLY; --읽기 전용 옵션
SELECT *
FROM STUDENT_VIEW;

SELECT *
FROM EMP;


CREATE OR REPLACE VIEW EMP_VIEW AS
SELECT EMPNO, ENAME, HIREDATE
FROM EMP
WITH READ ONLY;
SELECT *
FROM EMP_VIEW;

--VIEW에서 수정 가능한 경우
--1.하나의 테이블만 참조 (조인 없을 때)
--2. GROUP 함수 없을 때 
--3. DISTINCT 가 없을 때
--4.** 읽기 전용 옵션이 없을 때 **
-- -> VIEW를 만들 때는 읽기 전용 옵션을 붙여주는게 좋다.

CREATE OR REPLACE VIEW STUDENT_VIEW AS
SELECT S.STU_NO,STU_NAME,STU_DEPT,AVG(ENR_GRADE) AS AVG_ENR
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO,STU_NAME,STU_DEPT;

SELECT * FROM STUDENT_VIEW;