-- STUDENT, ENROL, SUBJECT 
-- 1. 성이 '김'씨인 학생들의 학번, 이름, 학과를 출력하시오.
SELECT STU_NO,STU_NAME,STU_DEPT
FROM STUDENT
WHERE SUBSTR(STU_NAME,1,1) = '김';
-- 2. 15학번 학생들의 학번, 이름, 학과를 출력하시오.
SELECT STU_NO,STU_NAME,STU_DEPT
FROM STUDENT
WHERE SUBSTR(STU_NO,2) LIKE '%15%';
-- 3. 컴퓨터정보 학과 학생들의 시험 평균 점수를 구하시오.
SELECT STU_DEPT,AVG(ENR_GRADE) 
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT
HAVING STU_DEPT = '컴퓨터정보';
-- 4. 컴퓨터개론 수업을 듣는 학생의 학번, 이름, 학과, 시험점수를 구하시오.
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;
SELECT S.STU_NO,STU_NAME,STU_DEPT,ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SJ ON E.SUB_NO = SJ.SUB_NO
WHERE SUB_NAME = '컴퓨터개론';
-- 5. 학생들의 전체 평균 키보다 큰 키를 가진 학생들의 학번, 이름, 키를 출력하시오.
SELECT STU_NO, STU_NAME, STU_HEIGHT
FROM STUDENT
WHERE STU_HEIGHT > (SELECT AVG(STU_HEIGHT)
FROM STUDENT);

-- 6. 본인 학과의 평균 키보다 큰 학생들의 이름, 학과, 키, 학과 평균키 값 출력
SELECT S.STU_NAME,
       S.STU_DEPT,
       S.STU_HEIGHT
FROM STUDENT S
WHERE S.STU_HEIGHT > (
    SELECT AVG(STU_HEIGHT)
    FROM STUDENT
    WHERE STU_DEPT = S.STU_DEPT
);
-- EMP, SALGRADE, DEPT
-- 1. 급여 등급이 3이상인 사원의 사번, 이름, 급여등급을 출력하시오.
SELECT EMPNO,ENAME,S.GRADE
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE S.GRADE >= 3;
-- 2. 사번, 이름, 팀장(MGR)의 이름을 출력하시오.
SELECT E1.EMPNO,E1.ENAME,E2.ENAME AS MGR
FROM EMP E1
INNER JOIN EMP E2 ON E1.EMPNO = E2.MGR;

-- 3. 부서별 가장 높은 급여를 받는 사원의 사번, 이름, 급여, 부서명을 출력하시오.
SELECT E.EMPNO,E.ENAME, E.SAL,D.DNAME
FROM EMP E
INNER JOIN DEPT D 
    ON E.DEPTNO = D.DEPTNO
WHERE E.SAL = (
    SELECT MAX(SAL)
    FROM EMP
    WHERE DEPTNO = E.DEPTNO
);

-- 4. 입사년도가 1981년도인 사원들의 급여 총합을 구하시오.
SELECT * FROM EMP;
SELECT * FROM SALGRADE;
SELECT * FROM DEPT;

SELECT SUM(SAL)
FROM EMP
WHERE SUBSTR(HIREDATE,1,2) = '81';
-- STU, PROFESSOR, DEPARTMENT
-- 1. 남자이면서(주민번호 7번째자리 1) 공과대학에 속한 학생의 수를 구하시오.
SELECT * FROM STU;
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

SELECT COUNT(*)
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE SUBSTR(S.JUMIN,7,1) = '1' AND D3.DNAME = '공과대학';
-- 2. 학생들의 아이디의 마지막 세글자를 '*' 로 채우시오
SELECT SUBSTR(ID, 1, LENGTH(ID) - 3) || '***' 
FROM STU;
-- 3. 보너스+급여가 400 이하인 교수들의 이름, 아이디, 학과명을 출력하시오.
SELECT P.NAME,P.ID,DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON D.DEPTNO = P.DEPTNO
WHERE PAY+BONUS <= 400;

-- 4. 담당 학생이 2명이상인 교수의 이름, 아이디, 담당학생 수를 출력하시오.
SELECT P.NAME,P.ID,COUNT(*)
FROM STU S
INNER JOIN PROFESSOR P ON S.PROFNO = P.PROFNO
GROUP BY P.NAME,P.ID
HAVING COUNT(*) >= 2;
-- EMP, SALGRADE, DEPT
-- 1. ALLEN과 같은 JOB, DEPTNO(부서)를 가진 사람을 구하시오.(ENAME, DNAME 출력)
SELECT * FROM EMP;
SELECT * FROM SALGRADE;
SELECT * FROM DEPT;

SELECT DNAME, ENAME
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE JOB = 'SALESMAN' AND E.DEPTNO = D.DEPTNO;
-- 2. 자신의 부서 급여등급 평균보다 높은 등급인 사람의 이름, 부서명, 급여등급을 구하시오.
SELECT E1.ENAME,
       D.DNAME,
       S1.GRADE
FROM EMP E1
INNER JOIN DEPT D 
    ON E1.DEPTNO = D.DEPTNO
INNER JOIN SALGRADE S1 
    ON E1.SAL BETWEEN S1.LOSAL AND S1.HISAL
WHERE S1.GRADE > (
    SELECT AVG(S2.GRADE)
    FROM EMP E2
    INNER JOIN SALGRADE S2
        ON E2.SAL BETWEEN S2.LOSAL AND S2.HISAL
    WHERE E2.DEPTNO = E1.DEPTNO
);

-- STUDENT, ENROL, SUBJECT
-- 1. 컴퓨터정보과의 평균보다 평균이 낮은 학과의 학과명, 점수 출력
SELECT STU_DEPT,
       AVG(ENR_GRADE) AS 평균점수
FROM STUDENT S
INNER JOIN ENROL E
    ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT
HAVING AVG(ENR_GRADE) < (
    SELECT AVG(E2.ENR_GRADE)
    FROM STUDENT S2
    INNER JOIN ENROL E2
        ON S2.STU_NO = E2.STU_NO
    WHERE S2.STU_DEPT = '컴퓨터정보'
);

-- STU, PROFESSOR, DEPARTMENT
-- 1. 가장 많은 학생이 있는 학과와 가장 적은 학생이 있는 학과의 학과명, 학생수를 출력하시오.
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

SELECT STU_DEPT,
       COUNT(*) AS 학생수
FROM STUDENT
GROUP BY STU_DEPT
HAVING COUNT(*) = (
        SELECT MAX(CNT)
        FROM (
            SELECT COUNT(*) CNT
            FROM STUDENT
            GROUP BY STU_DEPT
        )
)OR COUNT(*) = (
        SELECT MIN(CNT)
        FROM (
            SELECT COUNT(*) CNT
            FROM STUDENT
            GROUP BY STU_DEPT
        )
);
