SELECT * FROM BOOK;
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;

SELECT
    BOOKNAME,PUBLISHER
FROM BOOK
WHERE PRICE >= 10000
UNION ALL
SELECT
    BOOKNAME,PUBLISHER
FROM BOOK
WHERE PUBLISHER = '굿스포츠'
ORDER BY BOOKNAME;

--날짜별 수익
SELECT DY,SP
FROM(   
    SELECT
    TO_CHAR(ORDERDATE, 'YYYY-MM-DD') AS DY ,SUM(SALEPRICE) AS SP,1 AS ORDERKEY
    FROM ORDERS
    GROUP BY ORDERDATE
    UNION
    SELECT
        '매출총액',SUM(SALEPRICE),2 AS ORDERKEY
        FROM ORDERS
    ORDER BY ORDERKEY , SP DESC
);

--책 가격이 가장 높은 상위 3개의 책이름, 가격 출력
SELECT ROWNUM , B.*
FROM(
    SELECT BOOKNAME,PRICE
    FROM BOOK B
    GROUP BY BOOKNAME,PRICE
    ORDER BY PRICE DESC
) B
WHERE ROWNUM <= 3;


SELECT *
FROM BOOK;

SELECT *
FROM BOOK
WHERE BOOKNAME LIKE '%축구%';

--날짜별 매출 
--날짜 ,해달 날짜의 ㅐ출, 매출이 20000이상일 경우 '상'
--10000이상일 경우 '중'  , 그외는 '하'로 표기
SELECT ORDERDATE,SUM(SALEPRICE),
    CASE
        WHEN SUM(SALEPRICE) > 20000 THEN '상'
        WHEN SUM(SALEPRICE) > 1000 THEN '중'
        ELSE '하'
    END 매출정보
FROM ORDERS
GROUP BY ORDERDATE;



