SELECT * FROM BOOK;
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;
​
--1. 구매자 이름, 책 이름, 구매일 출력

SELECT NAME, BOOKNAME,ORDERDATE
FROM BOOK B
INNER JOIN ORDERS O ON B.BOOKID = O.BOOKID
INNER JOIN CUSTOMER C ON C.CUSTID = O.CUSTID;
