--ROWNUM

SELECT ROWNUM,  S.*
FROM STUDENT S
WHERE ROWNUM <=5
ORDER BY STU_HEIGHT;

SELECT ROWNUM,  S.*
FROM STUDENT S
ORDER BY STU_HEIGHT;

SELECT ROWNUM, S.*
FROM(
    SELECT *
    FROM STUDENT
    WHERE STU_HEIGHT IS NOT NULL
    ORDER BY STU_HEIGHT DESC
) S 
WHERE ROWNUM <=5;

--시험 평균 점수 상위 3명의 학번, 이름, 평균점수 출력
SELECT ROWNUM, S.*
FROM(
    SELECT S.STU_NO , STU_NAME ,AVG(ENR_GRADE)
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY S.STU_NO,STU_NAME
    ORDER BY AVG(ENR_GRADE) DESC
)S
WHERE ROWNUM <= 3;
