SELECT DECODE(SUBSTR(JUMIN,7,1),1,'남자','여자')
FROM STU;

SELECT SYSDATE
FROM DUAL;

SELECT MAX(STU_HEIGHT)
FROM STUDENT;

SELECT ROUND(AVG(SAL),2)
FROM EMP;

SELECT EMPNO,ENAME,JOB
FROM EMP
WHERE SAL = ( 
    SELECT MAX(SAL)
    FROM EMP
);

SELECT JOB,ROUND(AVG(SAL),2)
FROM EMP
WHERE SAL >= 1500
GROUP BY JOB
HAVING AVG(SAL) >= 2500;

SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE)
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME;

SELECT S.STU_NO, AVG(ENR_GRADE) AVG_GRADE
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO;

SELECT *
FROM STUDENT S
INNER JOIN(
    SELECT S.STU_NO, AVG(ENR_GRADE) AVG_GRADE
    FROM STUDENT S
    LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY S.STU_NO
) T ON S.STU_NO = T.STU_NO;

SELECT S.*,ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

SELECT E1.*, E2.ENAME 매니저이름
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;

SELECT *
FROM DEPARTMENT;

SELECT *
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE NAME = '서진수';

SELECT *
FROM STUDENT;
SELECT *
FROM ENROL;
SELECT * FROM SUBJECT;
SELECT *
FROM EMP E
INNER JOIN SALGRADE ON E.SAL BETWEEN LOSAL AND HISAL;
-- STUDENT, ENROL, SUBJECT
-- 1. 학번, 학생이름, 학과, 시험과목명, 시험점수 출력
SELECT S.STU_NO, STU_NAME , STU_DEPT,SUB_NAME,ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SJ ON SJ.SUB_NO = E.SUB_NO;
-- 2. 각 학과별 시험 평균 점수 구하기(학과,평균점수 출력)
SELECT AVG(ENR_GRADE) , STU_DEPT
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT;
-- 3. 본인 학과의 시험 평균 점수보다 높은 평균 점수를 가진 학생의 학번, 이름, 평균점수 출력
SELECT S.STU_NO ,STU_NAME, ENR_GRADE,AVG
FROM STUDENT S
INNER JOIN(SELECT AVG(ENR_GRADE) AVG, STU_DEPT
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT) T ON S.STU_DEPT = T.STU_DEPT
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO 
WHERE AVG< ENR_GRADE;
-- 4. 시험을 2번이상 본 학생의 학번, 이름, 시험본 횟수 출력
SELECT S.STU_NO,COUNT(*) AS 시험본횟수,STU_NAME
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO,STU_NAME
HAVING COUNT(*) >= 2;
