--UNION, UNION ALL
--SELECT 쿼리 실행 결과를 합쳐주는 명령어

SELECT
    STU_NO,
    STU_NAME,
    STU_DEPT
FROM STUDENT
WHERE STU_HEIGHT >= 170
UNION -- 중복없이 하나로 합쳐서 출력
SELECT
    STU_NO,
    STU_NAME,
    STU_DEPT
FROM STUDENT
WHERE STU_WEIGHT >= 60;


SELECT
    STU_NO,
    STU_NAME,
    STU_DEPT
FROM STUDENT
WHERE STU_HEIGHT >= 170
UNION ALL-- 중복된 값을 그대로 출력
SELECT
    STU_NO,
    STU_NAME,
    STU_DEPT
FROM STUDENT
WHERE STU_WEIGHT >= 60;


--주의점
--1. 컴럼의 개수와 타입이 같아야 한다.
--2. 컬럼의 이름(별칭)은 먼저 나오는 쿼리를 따른다.
--3. 정렬(ORDET BY)는 맨 마지막 줄에 작성. 첫번째 쿼리 컬럼을 기준으로 한다.

SELECT STU_NAME AS ZZZ FROM STUDENT
UNION
SELECT COUNT(*) FROM STUDENT; -- 커럼의 데이터 타입이 달라서 오류 발생

SELECT STU_NAME AS ZZZ FROM STUDENT
UNION
SELECT STU_DEPT FROM STUDENT; --컬럼의 이름은 첫번째 쿼리를 따른다.

SELECT STU_DEPT, COUNT(*) 학생수
FROM STUDENT
GROUP BY STU_DEPT
UNION
SELECT '전체학생수' ,COUNT(*)
FROM STUDENT;

--학생별 시험 평균 점수 출ㄺ + 전체 학생의 평균 점수 출력
SELECT 
    STU_NAME,
    AVG(ENR_GRADE) AS AVG_GRADE,
    1 AS ORDERKEY
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME
UNION
SELECT
    '전체 학생의 평균'
    ,ROUND(AVG(ENR_GRADE),2),
    2 AS ORDETKEY
FROM ENROL
ORDER BY ORDERKEY, AVG_GRADE;

SELECT STU_NAME, AVG_GRADE
FROM(SELECT 
    STU_NAME,
    AVG(ENR_GRADE) AS AVG_GRADE,
    1 AS ORDERKEY
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME
UNION
SELECT
    '전체 학생의 평균'
    ,ROUND(AVG(ENR_GRADE),2),
    2 AS ORDETKEY
FROM ENROL
ORDER BY ORDERKEY, AVG_GRADE);