CREATE TABLE TBL_USER (
    USERID      VARCHAR2(20)   NOT NULL,
    PWD         VARCHAR2(100)  NOT NULL,
    USERNAME    VARCHAR2(20)   NOT NULL,
    BIRTH       DATE           NOT NULL,
    PHONE       VARCHAR2(20)   NOT NULL,
    GENDER      CHAR(1),
    EMAIL       VARCHAR2(30),
    RECOMMID    VARCHAR2(20),
    CDATETIME   DATE           NOT NULL,
    
    CONSTRAINT PK_TBL_USER PRIMARY KEY (USERID)
);


CREATE TABLE TBL_BOARD (
    BOARDNO     NUMBER         NOT NULL,
    USERID      VARCHAR2(20)   NOT NULL,
    TITLE       VARCHAR2(100)  NOT NULL,
    CONTENTS    VARCHAR2(300),
    CNT         NUMBER         NOT NULL,
    KIND        CHAR(1)        NOT NULL,
    CDATETIME   DATE           NOT NULL,
    UDATETIME   DATE           NOT NULL,
    
    CONSTRAINT PK_TBL_BOARD PRIMARY KEY (BOARDNO)
);

CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE TBL_COMMENT (
    COMMENTNO     NUMBER         NOT NULL,
    BOARDNO       NUMBER,
    USERID        VARCHAR2(20),
    CONTENTS       VARCHAR2(300),
    P_COMMENTNO   NUMBER,
    CDATETIME     DATE           NOT NULL,
    UDATETIME     DATE           NOT NULL,
    
    CONSTRAINT PK_TBL_COMMENT PRIMARY KEY (COMMENTNO)
);

CREATE SEQUENCE COMMENT_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO TBL_USER VALUES ('user01','pw01','홍길동',DATE '1990-01-01','010-1111-1111','M','user01@test.com',NULL,SYSDATE);
INSERT INTO TBL_USER VALUES ('user02','pw02','김영희',DATE '1992-02-02','010-2222-2222','F','user02@test.com','user01',SYSDATE);
INSERT INTO TBL_USER VALUES ('user03','pw03','이철수',DATE '1988-03-03','010-3333-3333','M','user03@test.com','user01',SYSDATE);
INSERT INTO TBL_USER VALUES ('user04','pw04','박민지',DATE '1995-04-04','010-4444-4444','F',NULL,NULL,SYSDATE);
INSERT INTO TBL_USER VALUES ('user05','pw05','최지훈',DATE '1993-05-05','010-5555-5555','M','user05@test.com','user02',SYSDATE);

INSERT INTO TBL_BOARD VALUES (BOARD_SEQ.NEXTVAL,'user01','공지사항 1','공지 내용입니다.',0,'1',SYSDATE,SYSDATE);
INSERT INTO TBL_BOARD VALUES (BOARD_SEQ.NEXTVAL,'user03','자유글 1','자유 게시판 글입니다.',0,'2',SYSDATE,SYSDATE);
INSERT INTO TBL_BOARD VALUES (BOARD_SEQ.NEXTVAL,'user03','질문 1','질문 있습니다.',0,'3',SYSDATE,SYSDATE);
INSERT INTO TBL_BOARD VALUES (BOARD_SEQ.NEXTVAL,'user01','자유글 2','두번째 자유글',0,'2',SYSDATE,SYSDATE);
INSERT INTO TBL_BOARD VALUES (BOARD_SEQ.NEXTVAL,'user05','공지사항 2','두번째 공지',0,'1',SYSDATE,SYSDATE);
INSERT INTO TBL_BOARD VALUES (BOARD_SEQ.NEXTVAL,'user01','질문 2','오라클 질문',0,'3',SYSDATE,SYSDATE);
INSERT INTO TBL_BOARD VALUES (BOARD_SEQ.NEXTVAL,'user01','자유글 3','오늘 날씨 좋네요',0,'2',SYSDATE,SYSDATE);
INSERT INTO TBL_BOARD VALUES (BOARD_SEQ.NEXTVAL,'user02','공지사항 3','세번째 공지',0,'1',SYSDATE,SYSDATE);
INSERT INTO TBL_BOARD VALUES (BOARD_SEQ.NEXTVAL,'user02','질문 3','SQL이 안돼요',0,'3',SYSDATE,SYSDATE);
INSERT INTO TBL_BOARD VALUES (BOARD_SEQ.NEXTVAL,'user02','자유글 4','마지막 자유글',0,'2',SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,1,'user02','첫 댓글입니다.',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,1,'user04','두번째 댓글',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,1,'user05','대댓글입니다.',1,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,2,'user05','좋은 글이네요.',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,2,'user04','동의합니다.',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,3,'user02','답변 기다립니다.',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,3,'user01','저도 궁금해요.',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,3,'user05','대댓글 테스트',6,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,4,'user04','재밌네요.',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,4,'user05','감사합니다.',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,5,'user02','공지 확인했습니다.',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,5,'user03','수고하셨습니다.',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,6,'user04','저도 같은 문제입니다.',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,6,'user05','해결되셨나요?',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,7,'user01','좋은 하루 되세요.',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,7,'user02','네 감사합니다.',15,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,8,'user03','공지 잘봤습니다.',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,8,'user04','확인 완료.',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,9,'user05','질문 있습니다.',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,9,'user02','무엇이 궁금하신가요?',19,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,10,'user04','마지막 댓글1',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,10,'user03','마지막 댓글2',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,10,'user04','마지막 댓글3',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL,10,'user05','마지막 댓글4',NULL,SYSDATE,SYSDATE);
INSERT INTO TBL_COMMENT VALUES (COMMENT_SEQ.NEXTVAL, 5, 'user01', '추가된 25번째 댓글입니다.', NULL, SYSDATE, SYSDATE);

SELECT COUNT(*) FROM TBL_USER;
SELECT COUNT(*) FROM TBL_BOARD;
SELECT COUNT(*) FROM TBL_COMMENT;


SELECT * FROM TBL_USER;
SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_COMMENT;

-- 게시글 제목, 내용, 조회수 ,작성자 이름 출력
SELECT TITLE, CONTENTS , CNT, USERNAME
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID;

--사용자 아이디 , 이름 , 해당 사용자가 작성한 댓글 개수 출력
SELECT U.USERID, USERNAME ,댓글개수
FROM TBL_USER U
INNER JOIN (
    SELECT USERID, COUNT(*) AS 댓글개수
    FROM TBL_COMMENT
    GROUP BY USERID
) T ON U.USERID = T.USERID;


--작성한 게시글의 조회수 합이 가장 많은 상위 3명의 이름과 조회수 합 출력
SELECT USERNAME, SUM_CNT
FROM(
    SELECT USERID, SUM(CNT) AS SUM_CNT
    FROM TBL_BOARD
    GROUP BY USERID
    ORDER BY SUM_CNT DESC
) T
INNER JOIN TBL_USER U ON T.USERID = U.USERID
WHERE ROWNUM <= 3;

SELECT 제목, 댓글개수
FROM(
    SELECT TITLE AS 제목,COUNT(*) AS 댓글개수,1 AS ORDERKEY
    FROM TBL_BOARD TB
    INNER JOIN TBL_COMMENT TC ON TB.BOARDNO = TC.BOARDNO
    GROUP BY TB.BOARDNO, TITLE
    UNION
    SELECT '댓글전체개수',COUNT(*),2 AS ORDERKEY
    FROM TBL_COMMENT
    ORDER BY ORDERKEY, 댓글개수 DESC
);



