SELECT 
    ENAME, SAL,
    RANK() OVER (ORDER BY SAL DESC) AS RANK1,
    DENSE_RANK() OVER (ORDER BY SAL DESC) AS RANK2,
    ROW_NUMBER() OVER (ORDER BY SAL DESC, ENAME DESC) AS RANK3
FROM EMP;

SELECT 
    ENAME, SAL,DEPTNO,
    RANK() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) AS RANK1
FROM EMP;