--1. 레코드 하나 INSERT,UPDATE,DELETE순으로 진행
--2.LIKE를 사용한 검색
--3.SUBSTR 함수를 이용한 문제
--4.조건에 맞게 VIEW만들기
--5~9. 조인(INNER,OUTER-LEFT,SELF), 서브쿼리
--10~12. 랜덤 


INSERT INTO TBL_EMP(EMP_ID, EMP_NAME,JOB_TITLE,SALARY,DEPT_ID)
VALUES ('2001','김개발','사원',1000000,'D01');
COMMIT;
SELECT * FROM TBL_EMP;

UPDATE TBL_EMP SET
SALARY = 38000
WHERE EMP_ID = '2001';
COMMIT;

DELETE FROM TBL_EMP WHERE EMP_ID = '2001';
COMMIT;

SELECT EMP_NAME,JOB_TITLE,SALARY
FROM TBL_EMP
WHERE EMP_NAME LIKE '김%';

SELECT SUBSTR(EMP_NAME,1,1)
FROM TBL_EMP;

CREATE OR REPLACE VIEW VW_HIGH_SAL AS
SELECT *
FROM TBL_EMP
WHERE SALARY >=4000;


SELECT EMP_NAME,DEPT_NAME,SALARY
FROM TBL_EMP E
INNER JOIN TBL_DEPT D ON E.DEPT_ID = D.DEPT_ID;

SELECT *
FROM TBL_EMP E
LEFT JOIN TBL_DEPT D ON E.DEPT_ID = D.DEPT_ID;


