SELECT *
FROM STUDENT
WHERE STU_GENDER != 'M';
CREATE OR REPLACE FUNCTION GENDER_FUNC(I_JUMIN IN VARCHAR2)
    RETURN VARCHAR2
IS
BEGIN
    IF LENGTH(I_JUMIN) !=13 THEN 
        RETURN '13자리 값을 입력하세요';
    ELSIF SUBSTR(I_JUMIN,7,1) = 1 OR SUBSTR(I_JUMIN,7,1) = 3 THEN 
        RETURN '남자';
    ELSIF SUBSTR(I_JUMIN,7,1) = 2 OR SUBSTR(I_JUMIN,7,1) = 4 THEN 
        RETURN '여자';
    ELSE
        RETURN '잘못된 값';
    END IF;
    
END;
/


SELECT NAME ,GENDER_FUNC(JUMIN)
FROM STU;

SELECT S.STU_NAME,
       S.STU_DEPT,
       S.STU_HEIGHT
FROM STUDENT S
WHERE S.STU_HEIGHT > (
    SELECT AVG(STU_HEIGHT)
    FROM STUDENT
    WHERE STU_DEPT = S.STU_DEPT
);


SELECT DNAME,COUNT(*)
FROM STU S
INNER JOIN DEPARTMENT D ON S.DEPTNO1 = D.DEPTNO
GROUP BY DNAME
HAVING COUNT(*) IN (SELECT MAX(COUNT(*))
FROM STU
GROUP BY DEPTNO1
UNION
SELECT MIN(COUNT(*))
FROM STU
GROUP BY DEPTNO1);