SELECT 
    STU_DEPT,
    COUNT(*) NUM
FROM STUDENT
GROUP BY STU_DEPT;

SELECT JOB ,AVG(SAL)
FROM EMP
GROUP BY JOB;

-- 학번,이름, 시험점수
SELECT S.STU_NO, STU_NAME, ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;
--사번,이름,급여,등급
SELECT EMPNO, ENAME,SAL,GRADE
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;

---학번,이름,시험평균점수
SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME;

--셀프 조인(SELF JOIN)
SELECT E1.EMPNO, E1.ENAME, E2.ENAME AS MANAGER
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;


--
SELECT *
FROM DEPARTMENT;


SELECT PROFNO, NAME, D1.DNAME, D2.DNAME , D3.DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D1 ON P.DEPTNO = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO;

--STUDENT, ENROL ,SUBJECT
--PROFESSOR, STU, DEPARTMENT
--EMP, DEPT,SALGRADE
SELECT *
FROM ENROL;
SELECT *
FROM SUBJECT;
SELECT *
FROM STUDENT;
-- STUDENT, ENROL, SUBJECT
--1. 컴퓨터개론 수업을 들은 학생의 학번, 이름, 시험점수 출력
SELECT STU_NAME, S.STU_NO, SUB_NAME, ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SJ ON E.SUB_NO = SJ.SUB_NO
WHERE SUB_NAME = '컴퓨터개론';

--2. 시험의 평균 점수가 70이상인 학생의 학번, 이름, 평균점수 출력
SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE)AS 평균
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME
HAVING AVG(ENR_GRADE) > 70;

--3. 시험을 2개이상 본 학생의 학번, 이름, 시험개수 출력
SELECT S.STU_NO, STU_NAME ,COUNT(*)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME
HAVING COUNT(*) >=2;
SELECT *
FROM EMP;
SELECT *
FROM DEPT;
SELECT *
FROM SALGRADE;
-- EMP, DEPT, SALGRADE
--1. 부서 이름, 부서의 급여 평균 등급 출력
SELECT DNAME ,ROUND(AVG(GRADE),1)
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY DNAME;
--2. 상사가 'BLAKE'인 사원들의 사번, 이름 출력
SELECT E1.EMPNO, E1.ENAME, E2.ENAME AS 상사
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO 
WHERE E2.ENAME = 'BLAKE';


-----------------------------------------------------------------------------
SELECT * 
FROM(
    SELECT DNAME,ROUND(AVG(SAL),1) AS SAL_AVG
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY DNAME
) T
INNER JOIN SALGRADE S ON T.SAL_AVG BETWEEN S.LOSAL AND S.HISAL ;
--PROFESSOR, STU, DEPARTMENT
--'공과대학'에 속한 학생의 수 구하기 (DEPTNO1 기준)
SELECT * FROM STU;
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;
SELECT COUNT(*)
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE D3.DNAME = '공과대학';