--outer join(left,right)

SELECT STU_NAME , COUNT(*)
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME;


SELECT * FROM PROFESSOR;
SELECT * FROM STU;

SELECT P.NAME , P.POSITION, NVL(S.NAME, '담당학생없음')
FROM PROFESSOR P
LEFT JOIN STU S ON P.PROFNO = S.PROFNO;

--학번, 학생 이름 ,담당 교수 이름 출력
SELECT S.STUNO, S.NAME ,NVL(P.NAME, '담당교수없음')
FROM STU S
LEFT JOIN PROFESSOR P  ON S.PROFNO = P.PROFNO;

--점수없으면 '점수 없음'

SELECT STU_NAME, NVL(TO_CHAR(AVG(ENR_GRADE), '점수없음')
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME;

--EMP
--부하직원의 수를 구하고 싶다
--없으면 0으로 출력 사번, 이름 ,자신의 부하직원수
SELECT *FROM EMP;
SELECT MGR, COUNT(*)
FROM EMP 
WHERE MGR IS NOT NULL
GROUP BY MGR;

SELECT EMPNO,ENAME,NVL(CNT,0) AS CNT
FROM EMP E
LEFT JOIN(
    SELECT MGR, COUNT(*) AS CNT
    FROM EMP 
    WHERE MGR IS NOT NULL
    GROUP BY MGR
) T ON T.MGR = E.EMPNO
ORDER BY CNT DESC;

SELECT 
    LPAD('*',INSTR(EMAIL,'@')-1,'*') || '@' || 
    LPAD('*',(INSTR(EMAIL,'.')-INSTR(EMAIL,'@')-1),'*') || 
    SUBSTR(EMAIL,INSTR(EMAIL,'.')) AS SECRETEMAIL, EMAIL 
FROM PROFESSOR;

SELECT
    EMAIL,
    RPAD('*', INSTR(EMAIL,'@')-1, '*')
    || '@' ||
    RPAD('*',(INSTR(EMAIL,'.')-INSTR(EMAIL,'@')-1),'*') ||
    SUBSTR(EMAIL,INSTR(EMAIL,'.')) AS SECRETEMAIL, EMAIL 
FROM PROFESSOR;
