--서브 쿼리


--1-1. STUDENT 테이블에서 학과별 평균 키
SELECT STU_DEPT, AVG(STU_HEIGHT) AVG_DEPT
FROM STUDENT
GROUP BY STU_DEPT;
-- 1.2. 학번, 이름, 학과 ,키, 내가 속한 학과의 평균 키
SELECT STU_NO, STU_NAME, S.STU_DEPT, STU_HEIGHT,ROUND(AVG_DEPT,1)
FROM STUDENT S
INNER JOIN (
    SELECT STU_DEPT, AVG(STU_HEIGHT) AVG_DEPT
    FROM STUDENT
    GROUP BY STU_DEPT
) T ON S.STU_DEPT = T.STU_DEPT;
--1-3. 내가속한 학과의 평균키보다 키가 큰 학생의 학번,이름,학과,키
SELECT STU_NO, STU_NAME, S.STU_DEPT, STU_HEIGHT,ROUND(AVG_DEPT,1)
FROM STUDENT S
INNER JOIN (
    SELECT STU_DEPT, AVG(STU_HEIGHT) AVG_DEPT
    FROM STUDENT
    GROUP BY STU_DEPT
) T ON S.STU_DEPT = T.STU_DEPT
WHERE AVG_DEPT < STU_HEIGHT;


--EMP , DEPT
--각 직급(POSITION)별 가장 많은 급여를 받는 사람의
--교수번호, 이름 ,급여 출력

--내가 속한 부서의 평균 급여보다 높은 급여를 받는 사람의 사번,이름,급여,부서이름
--속한 부서의 평균급여 출력
SELECT P.NAME,
       D2.DNAME,
       P.PAY,
       T.AVG_PAY
FROM PROFESSOR P
INNER JOIN DEPARTMENT D1
    ON P.DEPTNO = D1.DEPTNO
INNER JOIN DEPARTMENT D2
    ON D1.PART = D2.DEPTNO
INNER JOIN (
    SELECT D2.DEPTNO,
           AVG(P.PAY) AS AVG_PAY
    FROM PROFESSOR P
    INNER JOIN DEPARTMENT D1
        ON P.DEPTNO = D1.DEPTNO
    INNER JOIN DEPARTMENT D2
        ON D1.PART = D2.DEPTNO
    GROUP BY D2.DEPTNO
) T
    ON D2.DEPTNO = T.DEPTNO
WHERE P.PAY > T.AVG_PAY;
SELECT *FROM EMP;
SELECT *FROM DEPT;
--EMP 테이블
--부서별 가장 높은 급여를 받는 사람의 사번, 이름 ,급여 출력

SELECT EMPNO,ENAME,SAL, MAX_SAL
FROM EMP E
INNER JOIN(
SELECT DEPTNO ,MAX(SAL) MAX_SAL
FROM EMP E
GROUP BY DEPTNO
) T ON E.DEPTNO = T.DEPTNO AND MAX_SAL = SAL;

--STUDENT
--학과별 가장 큰 키를 가진 학생의 학번, 이름 ,키 출력
SELECT *FROM STUDENT;

SELECT STU_NO, STU_NAME , STU_HEIGHT
FROM STUDENT S
INNER JOIN(
SELECT STU_DEPT,MAX(STU_HEIGHT) MAX_HEIGHT
FROM STUDENT S
GROUP BY STU_DEPT
) T ON S.STU_DEPT = T.STU_DEPT AND MAX_HEIGHT = STU_HEIGHT;
--
SELECT SUBSTR(STUNO,1,2),AVG(HEIGHT)
FROM STU
GROUP BY SUBSTR(STUNO,1,2);
--남자와 여자의 평균 키 출력

SELECT DECODE(SUBSTR(JUMIN,7,1),1,'남',3,'남자','여'),ROUND(AVG(HEIGHT),1)
FROM STU
GROUP BY SUBSTR(JUMIN,7,1);

-- 
